import re
from pathlib import Path

import markdown


SECTION_PATTERN = re.compile(r"^## \d+\.\s+", re.MULTILINE)

SECTION_IDS = ["summary", "tech-stack", "structure", "quality", "improvements", "security"]

SECTION_TITLES = [
    "Project Summary",
    "Tech Stack",
    "Structure & Architecture",
    "Code Quality",
    "Suggested Improvements",
    "Security Issues",
]


def generate_html(markdown_content: str, repo_name: str) -> str:
    """Parse a Markdown report and generate a styled HTML page.

    Args:
        markdown_content: The full Markdown report with 6 sections.
        repo_name: Repository name for the page header.

    Returns:
        Complete HTML document as a string.
    """
    sections = _parse_sections(markdown_content)
    return _build_html(repo_name, sections)


def get_stylesheet() -> str:
    """Return the content of the CSS stylesheet."""
    css_path = Path(__file__).parent / "style.css"
    return css_path.read_text(encoding="utf-8")


def _parse_sections(markdown_content: str) -> list[str]:
    """Split the Markdown report into sections by ## N. headers.

    Returns:
        List of HTML strings, one per section. If fewer than 6 sections
        are found, empty strings fill the remaining slots.
    """
    parts = SECTION_PATTERN.split(markdown_content)
    # First element is everything before the first ## N. header (usually empty)
    # Remaining elements are the section bodies (after the header text)
    section_bodies = []
    for part in parts[1:]:
        # The section title is on the first line, content follows
        lines = part.split("\n", 1)
        body = lines[1].strip() if len(lines) > 1 else ""
        section_bodies.append(_md_to_html(body))

    # Pad to 6 sections
    while len(section_bodies) < 6:
        section_bodies.append("<p>No data available.</p>")

    return section_bodies


def _md_to_html(md_content: str) -> str:
    """Convert a Markdown string to HTML using the markdown library."""
    return markdown.markdown(md_content, extensions=["tables"])


def _count_items(section_html: str) -> int:
    """Count table rows (excluding header) in a section to get the number of items."""
    # Count <tr> tags minus 1 for the header row
    rows = section_html.count("<tr>")
    return max(0, rows - 1) if rows > 0 else 0


def _build_html(repo_name: str, sections: list[str]) -> str:
    """Build the complete HTML document from parsed sections."""
    initial = repo_name[0].upper() if repo_name else "?"

    improvements_count = _count_items(sections[4])
    security_count = _count_items(sections[5])

    cards_html = ""
    for i, (section_id, title, content) in enumerate(
        zip(SECTION_IDS, SECTION_TITLES, sections)
    ):
        cards_html += f"""
  <section class="card" id="{section_id}">
    <h2><span class="section-num">{i + 1}</span> {title}</h2>
    {content}
  </section>
"""

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Analysis: {repo_name}</title>
  <link rel="stylesheet" href="style.css">
</head>
<body>
<div class="container">

  <header class="report-header">
    <div class="repo-name">
      <div class="icon">{initial}</div>
      {repo_name}
    </div>
    <div class="repo-url">Analyzed by repo-analyzer</div>
  </header>

  <div class="metrics">
    <div class="metric">
      <div class="label">Security Issues</div>
      <div class="value red">{security_count}</div>
    </div>
    <div class="metric">
      <div class="label">Improvements</div>
      <div class="value amber">{improvements_count}</div>
    </div>
  </div>

{cards_html}
  <footer>Generated by repo-analyzer</footer>

</div>
</body>
</html>
"""
